[package]
name = "file-explorer-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.0"
dioxus-desktop = "0.4.0"
dioxus-free-icons = "0.7.0"
dioxus-material-icons = "1.1.0"
